apiVersion: v1
kind: Pod
spec:
  serviceAccountName: manifest-deploy-job
  containers:
    - name: jnlp
      image: quay.io/openshift/origin-jenkins-agent-base:4.5
      args: ['$(JENKINS_SECRET)', '$(JENKINS_NAME)']
